### ISSUE TITLE
Code Review Day 5

### ISSUE THREAD

**Issue by benjp009** [Debas-31/dbus-portfolio#15]
# 👋  @Debas-31 

### Great job so far !! 

Please try to improve your presentation skills when presenting your project to us. 

I would make sure that the tags of languages are actually matching the languages used for the project. (HTML, CSS, JavaScript) and keep the correct writing way for the languages.

**Comment by RayhanTabase** [comment]
Great job Debas. Everything else looks great. 👍👍👍

**Comment by Debas-31** [comment]
- [ ] Thank you guys for constructive feedback @benjp009  and @RayhanTabase
